"""added verified field

Revision ID: 856cee11025d
Revises: b4b4bf29aaef
Create Date: 2025-08-27 09:12:36.491088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856cee11025d'
down_revision = 'b4b4bf29aaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('attempts')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
